name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Build
        run: CLEAN=1 ./build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: positiveparade.wasm
          name: positive-parade-wasm-${{ github.run_number }}
          if-no-files-found: error
